import { fileExtension } from "@/lib/file-preview";

/** Map file extension to react-syntax-highlighter language id. */
export function syntaxLanguageFromFileName(fileName: string): string {
  const ext = fileExtension(fileName);
  const map: Record<string, string> = {
    js: "javascript",
    jsx: "jsx",
    ts: "typescript",
    tsx: "tsx",
    mjs: "javascript",
    cjs: "javascript",
    json: "json",
    jsonc: "json",
    yaml: "yaml",
    yml: "yaml",
    toml: "toml",
    ini: "ini",
    xml: "xml",
    html: "html",
    htm: "html",
    css: "css",
    scss: "scss",
    sass: "scss",
    less: "less",
    sh: "bash",
    bash: "bash",
    zsh: "bash",
    fish: "bash",
    bat: "batch",
    cmd: "batch",
    ps1: "powershell",
    py: "python",
    rs: "rust",
    go: "go",
    java: "java",
    c: "c",
    cc: "cpp",
    cpp: "cpp",
    cxx: "cpp",
    h: "c",
    hh: "cpp",
    hpp: "cpp",
    hxx: "cpp",
    cs: "csharp",
    kt: "kotlin",
    kts: "kotlin",
    swift: "swift",
    rb: "ruby",
    php: "php",
    pl: "perl",
    lua: "lua",
    r: "r",
    sql: "sql",
    graphql: "graphql",
    gql: "graphql",
    proto: "protobuf",
    tf: "hcl",
    hcl: "hcl",
    dockerfile: "docker",
    makefile: "makefile",
    gradle: "gradle",
    patch: "diff",
    diff: "diff",
    md: "markdown",
    markdown: "markdown",
    mdx: "markdown",
  };
  return map[ext] ?? "text";
}
