// @generated by scripts/codegen-report-templates.mjs — do not edit
//! Template identifiers synced from packages/types/report-templates.json

pub const TEMPLATE_IDS: &[&str] = &[
    "cfe-long",
    "cfe-short",
    "expert-witness-frcp26",
    "engagement-letter",
    "pi-surveillance",
    "pi-background",
    "fraud-incident-log",
];

pub fn is_known_template(id: &str) -> bool {
    TEMPLATE_IDS.contains(&id)
}
